sqlite3_url_dev=jdbc:sqlite:C:/Users/royta/databases/UsefulTools.db
sqlite3_url=sqlite3_url=jdbc:sqlite:/databases/UsefulTools.db
sqlite3_driver=org.sqlite.JDBC
simple_formatter=java.util.logging.SimpleFormatter.format
format=[%1$tF %1$tT] [%4$-7s] %3$s - %5$s%n
RSA_CIPHER=RSA/ECB/OAEPWithSHA-256AndMGF1Padding
BCRYPT_LOG_ROUNDS=12
cors_allowed_origins=https://useful-tools.vercel.app,http://localhost:3000,http://localhost:5173