package PasswordGenerator.Utilities;

import java.security.KeyException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;

public class PasswordGeneratorUtils {
	public static Stream<Character> getRandomSpecialChars(int length) {  
        Stream<Character> specialCharsStream;  
        Random random = new SecureRandom();  
        // use ints() method of random to get IntStream of special chars of the specified length  
        IntStream specialChars = random.ints(length, 33, 126)
        		.filter(i -> !Character.isLetterOrDigit(i));
        specialCharsStream =  specialChars.mapToObj(data -> (char) data);   
        return specialCharsStream;  
    }
	public static Stream<Character> getRandomNumbers(int length) {  
        Stream<Character> numberStream;  
        Random random = new SecureRandom();  
        // use ints() method of random to get IntStream of number of the specified length  
        IntStream numberIntStream = random.ints(length, 48, 57);  
        numberStream = numberIntStream.mapToObj(data -> (char) data);  
        return numberStream;  
    }  
	public static Stream<Character> getRandomAlphabets(int length, boolean check) {  
        Stream<Character> lowerUpperStream;  
        // for lower case stream  
        if(check == true) {   
            Random random = new SecureRandom();  
            IntStream lCaseStream = random.ints(length, 'a', 'z');  
            lowerUpperStream =  lCaseStream.mapToObj(data -> (char) data);  
        }  
        // for upper case stream  
        else {    
            Random random = new SecureRandom();  
            IntStream uCaseStream = random.ints(length, 'A', 'Z');  
            lowerUpperStream =  uCaseStream.mapToObj(data -> (char) data);  
        }   
        return lowerUpperStream;  
    }  
    // creates an array of elements which signify length of each parameter - generated by Random
    public static int[] getRandomizedValues(int length) {
    	int val1 = (int) Math.floor(Math.random()*(length/3+1));
    	int val2 = (int) Math.floor(Math.random()*(length/3+1)+(length/3));
    	int val3 = (int) Math.floor(Math.random()*(length/3+1)+(2*length/3));
    	
    	int results[] = {val1, val2-val1, val3-val2, length-val3};
    	return results;
    }
    // create generateSecurePassword() method that finds the secure password
    public static String generateSecurePassword(int n, int spc, int uc, int lc) {
         Stream<Character> demoPassword = Stream.concat(getRandomNumbers(n),   
                 Stream.concat(getRandomSpecialChars(spc),   
                         Stream.concat(getRandomAlphabets(lc, true), getRandomAlphabets(uc, false))));  
        // create a list of Char that stores all the characters, numbers, and special characters   
        List<Character> listOfChar = demoPassword.collect(Collectors.toList());
        // use shuffle() method of the Collections to shuffle the list elements   
        Collections.shuffle(listOfChar);
        //generate a random string(secure password) by using list stream() method and collect() method  
        String password = listOfChar.stream()
                .collect(StringBuilder::new, StringBuilder::append, StringBuilder::append)  
                .toString();    
        return password;  
    }  
    public static String generateEncryptedPassword(String password) {
		String encryptedPassword = "";
		try {
			KeyPairGenerator keyGen = KeyPairGenerator.getInstance("RSA");
			keyGen.initialize(2048);
			KeyPair pair = keyGen.generateKeyPair();
			
			PublicKey publicKey = pair.getPublic();
			
			Cipher cipher = Cipher.getInstance("RSA");
			cipher.init(Cipher.ENCRYPT_MODE, publicKey);
			byte[] byteStreamPassword = cipher.doFinal(password.getBytes());
			
			encryptedPassword = Base64.getEncoder().encodeToString(byteStreamPassword);
		}
		catch(NoSuchAlgorithmException nsae) {
			nsae.printStackTrace();
		}
		catch(NoSuchPaddingException nspe) {
			nspe.printStackTrace();
		}
		catch(KeyException ike) {
			ike.printStackTrace();
		}
		catch(BadPaddingException bpe) {
			bpe.printStackTrace();
		}
		catch(IllegalBlockSizeException ibse) {
			ibse.printStackTrace();
		}
		return encryptedPassword;
	}
//    public static void main(String args[]) {
//    	Scanner sc = new Scanner(System.in);
//    	System.out.println("Enter the length of the password that you want to generate : ");
//    	int l = sc.nextInt();
//    	System.out.println("How many numbers do you want?");
//    	int n = sc.nextInt();
//    	System.out.println("How many special characters do you want?");
//    	int spc = sc.nextInt();
//    	System.out.println("How many uppercase letters do you want?");
//    	int uc = sc.nextInt();
//    	System.out.println("How many lowercase letters do you want?");
//    	int lc = sc.nextInt();
//        String pass = generateSecurePassword(n,spc,uc,lc);
//        System.out.println("Password generated is : "+pass);
//        String encPass = generateEncryptedPassword(pass);
//        System.out.println("Encrypted password is : "+encPass);
//        sc.close();
//    }
}
