import { chromium, expect } from '../../usefultools-frontend/node_modules/@playwright/test/index.mjs'
import { THEME_OPTIONS } from '../../usefultools-frontend/src/theme/themeOptions.js'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import assert from 'node:assert/strict'

const run = process.argv[2], output = path.join((await readFile('.local/ui-current.txt', 'utf8')).trim(), 'controls')
// Refuse reused evidence: a failed rerun must never leave an older PASS current.
await mkdir(output)
const sessions = JSON.parse(await readFile(path.join(run, 'sessions.json'), 'utf8')), origin = sessions.origin
assert(['localhost', '127.0.0.1'].includes(new URL(origin).hostname))
const browser = await chromium.launch({ channel: 'chrome', headless: true }), checks = [], scans = [], errors = [], blocked = []
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } }), identity = sessions.browseruser
  await context.addCookies([{ name: 'JSESSIONID', value: identity.session, url: origin, httpOnly: true }])
  await context.addInitScript(i => { localStorage.setItem('username', i.username); localStorage.setItem('_ut_role', i.role); sessionStorage.setItem('_ut_xsrf', i.csrf) }, identity)
  await context.route('**/*', route => {
    if (new URL(route.request().url()).origin !== origin) { blocked.push(route.request().url()); return route.abort() }
    return route.continue()
  })
  await context.route('**/__ui/axe.js', route => route.fulfill({ path: path.resolve('.b7/tools/node_modules/axe-core/axe.min.js'), contentType: 'application/javascript' }))
  const page = await context.newPage(); page.on('pageerror', e => errors.push(e.message))
  await page.goto(origin + '/backend-support', { waitUntil: 'networkidle' })
  const region = page.getByRole('region', { name: 'Schema generator', exact: true })
  const nullable = () => region.getByRole('checkbox', { name: 'Nullable', exact: true })
  const primary = () => region.getByRole('checkbox', { name: 'Primary key (selection order)', exact: true })
  const jsonButton = region.getByRole('button', { name: 'JSON', exact: true }), tablesButton = region.getByRole('button', { name: 'Tables', exact: true })
  async function specification() { await jsonButton.click(); const result = JSON.parse(await region.getByLabel('Schema generation JSON').inputValue()); await tablesButton.click(); return result }
  async function generate() {
    const response = page.waitForResponse(r => r.url().endsWith('/backend-support/generate'))
    await region.getByRole('button', { name: 'Validate and generate schema', exact: true }).click()
    const data = await (await response).json(); assert(data.success); return data.data
  }
  const original = await specification(), originalBundle = await generate()
  await page.evaluate(() => { window.__changes = 0; document.addEventListener('change', e => { if (e.target.matches('input[type=checkbox]')) window.__changes++ }) })
  await nullable().nth(1).locator('..').getByText('Nullable', { exact: true }).click()
  await expect(nullable().nth(1)).toBeChecked(); assert.equal(await page.evaluate(() => window.__changes), 1)
  await nullable().nth(1).click(); await expect(nullable().nth(1)).not.toBeChecked(); assert.equal(await page.evaluate(() => window.__changes), 2)
  await region.getByRole('combobox', { name: /^Logical type/ }).nth(1).focus(); await page.keyboard.press('Tab')
  await expect(nullable().nth(1)).toBeFocused()
  assert(await nullable().nth(1).evaluate(e => e.matches(':focus-visible') && getComputedStyle(e).outlineStyle !== 'none'))
  await page.keyboard.press('Space'); await expect(nullable().nth(1)).toBeChecked(); assert.equal(await page.evaluate(() => window.__changes), 3)
  await page.keyboard.press('Space'); await expect(nullable().nth(1)).not.toBeChecked()
  checks.push('label/control click and Tab/Space toggle once; native focus visible')
  await primary().nth(0).uncheck(); await primary().nth(1).check(); await primary().nth(0).check()
  assert.deepEqual((await specification()).tables[0].primaryKey, ['name', 'id'])
  await primary().nth(1).uncheck(); assert.deepEqual((await specification()).tables[0].primaryKey, ['id'])
  const count = await nullable().count(); await region.getByRole('button', { name: 'Add column', exact: true }).click()
  assert.equal(await nullable().count(), count + 1); await nullable().last().uncheck()
  await region.getByRole('button', { name: /Remove column column_/ }).click(); assert.equal(await nullable().count(), count)
  assert.deepEqual(await specification(), original)
  const restoredBundle = await generate(); assert.equal(restoredBundle.digest, originalBundle.digest)
  assert.deepEqual(restoredBundle.files, originalBundle.files)
  checks.push('composite PK selection order, deselection, dynamic rows and unchanged serialized/generated bytes')
  await jsonButton.click(); const reordered = structuredClone(original); reordered.tables[0].columns.reverse()
  await region.getByLabel('Schema generation JSON').fill(JSON.stringify(reordered)); await region.getByRole('button', { name: 'Apply JSON to forms', exact: true }).click(); await tablesButton.click()
  assert.equal(await region.getByLabel('Column database name', { exact: true }).first().inputValue(), 'active')
  await jsonButton.click(); await region.getByLabel('Schema generation JSON').fill(JSON.stringify(original)); await region.getByRole('button', { name: 'Apply JSON to forms', exact: true }).click(); await tablesButton.click()
  checks.push('JSON-supported row reorder preserves ID associations')
  await region.getByRole('combobox', { name: /^Schema source/ }).selectOption('sample')
  await expect(nullable().first()).toBeDisabled(); const previous = await nullable().first().isChecked()
  await nullable().first().locator('..').click({ force: true }); assert.equal(await nullable().first().isChecked(), previous)
  await region.getByRole('combobox', { name: /^Schema source/ }).selectOption('draft')
  await expect(nullable().first()).toBeEnabled(); checks.push('read-only sample disables controls without changing checked values')
  for (const theme of THEME_OPTIONS) {
    await page.evaluate(t => localStorage.setItem('usefultools.theme', t), theme.value); await page.reload({ waitUntil: 'networkidle' }); await page.evaluate(() => document.fonts.ready)
    await page.addScriptTag({ url: origin + '/__ui/axe.js' })
    for (const viewport of [{ width: 1440, height: 900 }, { width: 768, height: 1024 }, { width: 375, height: 812 }]) {
      await page.setViewportSize(viewport)
      const layout = await nullable().first().evaluate(e => {
        const label = e.labels[0], b = e.getBoundingClientRect(), l = label.getBoundingClientRect(), range = document.createRange()
        const text = [...label.childNodes].find(n => n.nodeType === Node.TEXT_NODE && n.textContent.trim()); range.selectNodeContents(text)
        const t = range.getBoundingClientRect()
        return { width: b.width, height: b.height, targetHeight: l.height, gap: t.left - b.right, centerDifference: Math.abs((b.top + b.bottom - t.top - t.bottom) / 2), associated: label.control === e, overflow: document.documentElement.scrollWidth > innerWidth + 1 }
      })
      assert(layout.width >= 18 && layout.width <= 20 && layout.height >= 18 && layout.targetHeight >= 24 && layout.gap >= 8 && layout.centerDifference < 3 && layout.associated && !layout.overflow, JSON.stringify({ theme, viewport, layout }))
    }
    await nullable().first().scrollIntoViewIfNeeded(); await page.screenshot({ path: path.join(output, theme.value + '-375.png') })
    const scan = await page.evaluate(async () => { const result = await axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21aa'] } }); return { version: result.testEngine.version, violations: result.violations.map(v => ({ id: v.id, impact: v.impact, targets: v.nodes.map(n => n.target) })), incomplete: result.incomplete.map(v => v.id) } })
    scans.push({ theme: theme.value, ...scan })
  }
  checks.push('ten themes across desktop/tablet/mobile: native glyph size, label target, alignment, no overflow; axe scans recorded')
  // Native desktop zoom changes the CSS viewport and device scale together.
  // CSS zoom alone leaves media-query widths unchanged and is not equivalent.
  const zoom = await context.newCDPSession(page)
  await zoom.send('Emulation.setDeviceMetricsOverride', { width: 320, height: 450, deviceScaleFactor: 2, mobile: false })
  await primary().first().scrollIntoViewIfNeeded()
  const wrapped = await primary().first().evaluate(e => {
    const box = e.getBoundingClientRect(), label = e.labels[0].getBoundingClientRect()
    return { wrapped: label.height > 40, contained: box.left >= label.left && box.right <= label.right,
      overflow: document.documentElement.scrollWidth > innerWidth + 1 }
  })
  assert(wrapped.wrapped && wrapped.contained && !wrapped.overflow, JSON.stringify(wrapped))
  // Capture through the same CDP session: Playwright screenshot resets emulated metrics.
  const zoomImage = await zoom.send('Page.captureScreenshot', { format: 'png', fromSurface: true, captureBeyondViewport: false })
  await writeFile(path.join(output, '200-percent-equivalent-reflow.png'), Buffer.from(zoomImage.data, 'base64'))
  checks.push('200% equivalent reflow: 640 physical px / 320 CSS px at device scale 2; wrapped labels contained, no overflow; native browser zoom remains manual')
  await zoom.send('Emulation.clearDeviceMetricsOverride'); await zoom.detach()
  assert.deepEqual(errors, []); assert.deepEqual(blocked, [])
  assert(scans.every(s => !s.violations.length), JSON.stringify(scans.filter(s => s.violations.length)))
  await writeFile(path.join(output, 'results.json'), JSON.stringify({ status: 'PASS', browser: browser.version(), checks, scans, errors, blocked }, null, 2))
  console.log(JSON.stringify({ status: 'PASS', checks }))
} catch (error) {
  await writeFile(path.join(output, 'failure.json'), JSON.stringify({ failure: String(error), checks, scans, errors, blocked }, null, 2)); throw error
} finally { await browser.close() }
