-- units.sql — reference data for UnitConverterPage
-- Regenerated from Debarun's upload with the following corrections applied:
--   1. Added the `offset` column (see notes below) so temperature can use the
--      same generic conversion formula as every other unit_type.
--   2. Fixed a missing comma between the lbf and kip rows (Force) — the INSERT
--      would not have parsed as valid SQL otherwise.
--   3. Fixed tonne-force (tf): was 980.665, should be 9806.65 (1000 kg x 9.80665
--      m/s^2) — off by exactly 10x.
--   4. Recategorized dyne (Force) from Imperial to Scientific — it's a CGS unit,
--      same class of fix as the earlier Gal/mGal/uGal correction.
--   5. Recomputed the Fahrenheit and Rankine factors for the new Kelvin-anchored
--      offset model (see the Temperature note below) — the previous factors (1.8
--      for both) were measuring something different (F/R degrees per 1 Celsius
--      degree) than what this column means for every other row (base units per 1
--      of this unit), and would silently produce wrong conversions if used as-is.
--
-- Temperature model: Kelvin is the anchor (factor=1, offset=0), matching the
-- convention that the SI unit is always the factor=1 row for its unit_type.
-- Generic conversion for ANY unit_type, including Temperature:
--     base   = value * factor + offset
--     result = (base - offsetB) / factorB
-- For every non-temperature row, offset=0, so this reduces exactly to the old
-- `value * factorA / factorB` formula — fully backward compatible.

CREATE TABLE IF NOT EXISTS units(
    id        INTEGER PRIMARY KEY,
    unit_id   VARCHAR NOT NULL,
    label     VARCHAR NOT NULL,
    category  VARCHAR NOT NULL,
    unit_type VARCHAR NOT NULL,
    symbol    VARCHAR NOT NULL,
    factor    REAL NOT NULL,
    offset    REAL NOT NULL DEFAULT 0,
    UNIQUE(unit_id, unit_type)
);

INSERT INTO units(unit_id, label, category, unit_type, symbol, factor, offset)
VALUES
      -- Length
      ('m', 'Meters', 'SI', 'Length', 'm', 1, 0),
      ('dam', 'Decameters', 'SI', 'Length', 'dam', 10, 0),
      ('hm', 'Hectometers', 'SI', 'Length', 'hm', 100, 0),
      ('km', 'Kilometers', 'SI', 'Length', 'km', 1000, 0),
      ('Mm', 'Megameters', 'SI', 'Length', 'Mm', 1000000, 0),
      ('Gm', 'Gigameters', 'SI', 'Length', 'Gm', 1000000000, 0),
      ('dm', 'Decimeters', 'SI', 'Length', 'dm', 0.1, 0),
      ('cm', 'Centimeters', 'SI', 'Length', 'cm', 0.01, 0),
      ('mm', 'Millimeters', 'SI', 'Length', 'mm', 0.001, 0),
      ('µm', 'Micrometers (Microns)', 'SI', 'Length', 'µm', 1e-06, 0),
      ('nm', 'Nanometers', 'SI', 'Length', 'nm', 1e-09, 0),
      ('pm', 'Picometers', 'SI', 'Length', 'pm', 1e-12, 0),
      ('Å', 'Angstrom', 'Scientific', 'Length', 'Å', 1e-10, 0),
      ('fm', 'Fermi', 'SI', 'Length', 'fm', 1e-15, 0),
      ('ft', 'Feet', 'Imperial', 'Length', 'ft', 0.3048, 0),
      ('in', 'Inches', 'Imperial', 'Length', 'in', 0.0254, 0),
      ('th', 'Thou / Mil', 'Imperial', 'Length', 'th', 2.54e-05, 0),
      ('yd', 'Yards', 'Imperial', 'Length', 'yd', 0.9144, 0),
      ('mi', 'Miles', 'Imperial', 'Length', 'mi', 1609.344, 0),
      ('nmi', 'Nautical Miles', 'Ocean Navigation', 'Length', 'nmi', 1852, 0),
      ('ftm', 'Fathom', 'Ocean Navigation', 'Length', 'ftm', 1.8288, 0),
      ('LD', 'Lunar Distance', 'Scientific', 'Length', 'LD', 384400000, 0),
      ('AU', 'Astronomical Units', 'Scientific', 'Length', 'AU', 149600000000, 0),
      ('ly', 'Light years', 'Scientific', 'Length', 'ly', 9460000000000000.0, 0),
      ('pc', 'Parsec', 'Scientific', 'Length', 'pc', 3.086e+16, 0),
      ('a0', 'Bohr Radius', 'Scientific', 'Length', 'a₀', 5.291772109e-11, 0),
      ('lp', 'Planck Length', 'Scientific', 'Length', 'ℓₚ', 1.616255e-35, 0),
      -- Mass
      ('kg', 'Kilograms', 'SI', 'Mass', 'kg', 1, 0),
      ('g', 'Grams', 'SI', 'Mass', 'g', 0.001, 0),
      ('mg', 'Milligrams', 'SI', 'Mass', 'mg', 1e-06, 0),
      ('t', 'Metric Tons', 'SI', 'Mass', 't', 1000, 0),
      ('dag', 'Decagrams', 'SI', 'Mass', 'dag', 0.01, 0),
      ('Gg', 'Gigagrams', 'SI', 'Mass', 'Gg', 1000000, 0),
      ('Tg', 'Teragrams', 'SI', 'Mass', 'Tg', 1000000000, 0),
      ('µg', 'Micrograms', 'SI', 'Mass', 'µg', 1e-09, 0),
      ('ng', 'Nanograms', 'SI', 'Mass', 'ng', 1e-12, 0),
      ('pg', 'Picograms', 'SI', 'Mass', 'pg', 1e-15, 0),
      ('fg', 'Femtograms', 'SI', 'Mass', 'fg', 1e-18, 0),
      ('lb', 'Pounds', 'Imperial', 'Mass', 'lb', 0.453592, 0),
      ('oz', 'Ounces', 'Imperial', 'Mass', 'oz', 0.0283495, 0),
      ('st', 'Stone', 'Imperial', 'Mass', 'st', 6.35029, 0),
      ('ozt', 'Troy Ounces', 'Imperial', 'Mass', 'ozt', 0.031103, 0),
      ('dwt', 'Pennyweight', 'Imperial', 'Mass', 'dwt', 0.00155515, 0),
      ('mp', 'Planck Mass', 'Scientific', 'Mass', 'mₚ', 2.176434e-08, 0),
      ('mSun', 'Solar Mass', 'Scientific', 'Mass', 'M☉', 1.989e+30, 0),
      ('mEarth', 'Earth Mass', 'Scientific', 'Mass', 'M⊕', 5.972e+24, 0),
      ('q', 'Quintals', 'SI', 'Mass', 'q', 100, 0),
      ('cwt', 'Hundredweights', 'Imperial', 'Mass', 'cwt', 50.8, 0),
      -- Temperature
      ('C', 'Celsius', 'Scientific', 'Temperature', '°C', 1, 273.15),
      ('F', 'Fahrenheit', 'Scientific', 'Temperature', '°F', 0.5555555555555556, 255.3722222222222),
      ('K', 'Kelvin', 'Scientific', 'Temperature', 'K', 1, 0),
      ('R', 'Rankine', 'Scientific', 'Temperature', '°R', 0.5555555555555556, 0),
      -- Time
      ('ms', 'Milliseconds', 'SI', 'Time', 'ms', 0.001, 0),
      ('μs', 'Microseconds', 'SI', 'Time', 'µs', 1e-06, 0),
      ('ns', 'Nanoseconds', 'SI', 'Time', 'ns', 1e-09, 0),
      ('ps', 'Picoseconds', 'SI', 'Time', 'ps', 1e-12, 0),
      ('s', 'Seconds', 'SI', 'Time', 's', 1, 0),
      ('min', 'Minutes', 'Common', 'Time', 'min', 60, 0),
      ('h', 'Hours', 'Common', 'Time', 'h', 3600, 0),
      ('d', 'Days', 'Common', 'Time', 'd', 86400, 0),
      ('week', 'Weeks', 'Common', 'Time', 'wk', 604800, 0),
      ('year', 'Years (365.25d)', 'Common', 'Time', 'yr', 31557600, 0),
      ('pt', 'Planck Time', 'Scientific', 'Time', 'tₚ', 5.391247e-44, 0),
      ('c', 'Century', 'Scientific', 'Time', 'c', 3155692600, 0),
      ('m', 'Millenium', 'Scientific', 'Time', 'm', 31556926000, 0),
      ('Ma', 'Mega annum', 'Scientific', 'Time', 'Ma', 31556926000000, 0),
      ('Ga', 'Giga annum', 'Scientific', 'Time', 'Ga', 3.1556926e+16, 0),
      -- Data Size
      ('b', 'Bits', 'Binary', 'Data Size', 'b', 1, 0),
      ('B', 'Bytes', 'Binary', 'Data Size', 'B', 8, 0),
      ('KB', 'Kilobytes (decimal)', 'Decimal', 'Data Size', 'KB', 8000, 0),
      ('MB', 'Megabytes (decimal)', 'Decimal', 'Data Size', 'MB', 8000000, 0),
      ('GB', 'Gigabytes (decimal)', 'Decimal', 'Data Size', 'GB', 8000000000, 0),
      ('TB', 'Terabytes (decimal)', 'Decimal', 'Data Size', 'TB', 8000000000000, 0),
      ('PB', 'Petabytes (decimal)', 'Decimal', 'Data Size', 'PB', 8000000000000000.0, 0),
      ('EB', 'Exabytes (decimal)', 'Decimal', 'Data Size', 'EB', 8e+18, 0),
      ('KiB', 'Kilobytes (binary)', 'Binary', 'Data Size', 'KiB', 8192, 0),
      ('MiB', 'Megabytes (binary)', 'Binary', 'Data Size', 'MiB', 8388608, 0),
      ('GiB', 'Gigabytes (binary)', 'Binary', 'Data Size', 'GiB', 8589934592, 0),
      ('TiB', 'Terabytes (binary)', 'Binary', 'Data Size', 'TiB', 8796093022208, 0),
      ('PiB', 'Petabytes (binary)', 'Binary', 'Data Size', 'PiB', 9007199254740992.0, 0),
      ('EiB', 'Exabytes (binary)', 'Binary', 'Data Size', 'EiB', 9.007199254740992e+18, 0),
      -- Speed
      ('ms', 'Metres/second', 'SI', 'Speed', 'm/s', 1, 0),
      ('mph', 'Miles/hour', 'Imperial', 'Speed', 'mph', 0.44704, 0),
      ('knot', 'Knots', 'Ocean Navigation', 'Speed', 'kn', 0.514444, 0),
      ('fts', 'Feet/second', 'Imperial', 'Speed', 'ft/s', 0.3048, 0),
      ('kms', 'Kilometres/second', 'SI', 'Speed', 'km/s', 1000, 0),
      ('cms', 'Centimetres/second', 'SI', 'Speed', 'cm/s', 0.01, 0),
      ('ips', 'Inches/second', 'Imperial', 'Speed', 'ips', 0.0254000000001016, 0),
      ('c', 'Speed of light', 'Scientific', 'Speed', 'c', 299792458, 0),
      ('Mach', 'Mach Number', 'Scientific', 'Speed', 'Mach', 343, 0),
      -- Acceleration
      ('ms2', 'Metres/sq. seconds', 'SI', 'Acceleration', 'm/s²', 1, 0),
      ('cms2', 'Centimetres/sq. seconds', 'SI', 'Acceleration', 'cm/s²', 0.01, 0),
      ('fts2', 'Feet/sq. seconds', 'Imperial', 'Acceleration', 'ft/s²', 0.3048, 0),
      ('kmh2', 'Kilometres/sq. hours', 'SI', 'Acceleration', 'km/h²', 7.72e-05, 0),
      ('mms2', 'Millimetres/sq. seconds', 'SI', 'Acceleration', 'mm/s²', 0.001, 0),
      ('Gal', 'Galileo', 'Scientific', 'Acceleration', 'Gal', 0.01, 0),
      ('mGal', 'Milligal', 'Scientific', 'Acceleration', 'mGal', 1e-05, 0),
      ('µGal', 'Microgal', 'Scientific', 'Acceleration', 'µGal', 1e-08, 0),
      ('mis2', 'Miles/sq. seconds', 'Imperial', 'Acceleration', 'mi/s²', 1609.344, 0),
      ('kms2', 'Kilometres/sq. seconds', 'SI', 'Acceleration', 'km/s²', 1000, 0),
      ('mph2', 'Miles/sq. hours', 'Imperial', 'Acceleration', 'mi/h²', 0.00012418, 0),
      ('g', 'Standard gravity (g-force)', 'Scientific', 'Acceleration', 'g', 9.80665, 0),
      ('mg', 'Milligravity', 'Scientific', 'Acceleration', 'mg', 0.00980665, 0),
      ('kns', 'Knots/second', 'Ocean Navigation', 'Acceleration', 'kn/s', 0.514444, 0),
      ('pa', 'Planck Acceleration', 'Scientific', 'Acceleration', 'aₚ', 5.5608e+51, 0),
      -- Area
      ('m2', 'Sq. Meters', 'SI', 'Area', 'm²', 1, 0),
      ('km2', 'Sq. Kilometers', 'SI', 'Area', 'km²', 1000000, 0),
      ('cm2', 'Sq. Centimeters', 'SI', 'Area', 'cm²', 0.0001, 0),
      ('ft2', 'Sq. Feet', 'Imperial', 'Area', 'ft²', 0.092903, 0),
      ('in2', 'Sq. Inches', 'Imperial', 'Area', 'in²', 0.000645, 0),
      ('acre', 'Acres', 'Imperial', 'Area', 'ac', 4046.86, 0),
      ('a', 'Ares', 'SI', 'Area', 'a', 100, 0),
      ('ha', 'Hectares', 'SI', 'Area', 'ha', 10000, 0),
      ('mm2', 'Sq. Millimeters', 'SI', 'Area', 'mm²', 1e-06, 0),
      ('dm2', 'Sq. Decimeters', 'SI', 'Area', 'dm²', 0.01, 0),
      ('yd2', 'Sq. Yards', 'Imperial', 'Area', 'yd²', 0.836127, 0),
      ('mi2', 'Sq. Miles', 'Imperial', 'Area', 'mi²', 2590000, 0),
      ('b', 'Barn', 'Scientific', 'Area', 'b', 1e-28, 0),
      ('pa', 'Planck Area', 'Scientific', 'Area', 'Aₚ', 2.612e-70, 0),
      -- Volume
      ('m3', 'Cu. Meters', 'SI', 'Volume', 'm³', 1, 0),
      ('km3', 'Cu. Kilometers', 'SI', 'Volume', 'km³', 1000000000, 0),
      ('cm3', 'Cu. Centimeters', 'SI', 'Volume', 'cm³', 1e-06, 0),
      ('dm3', 'Cu. Decimeters', 'SI', 'Volume', 'dm³', 0.001, 0),
      ('ft3', 'Cu. Feet', 'Imperial', 'Volume', 'ft³', 0.0283168, 0),
      ('in3', 'Cu. Inches', 'Imperial', 'Volume', 'in³', 1.6387064e-05, 0),
      ('L', 'Liters', 'SI', 'Volume', 'L', 0.001, 0),
      ('mL', 'Milliliters', 'SI', 'Volume', 'mL', 1e-06, 0),
      ('µL', 'Microliters', 'SI', 'Volume', 'µL', 1e-09, 0),
      ('nL', 'Nanoliters', 'SI', 'Volume', 'nL', 1e-12, 0),
      ('dL', 'Deciliters', 'SI', 'Volume', 'dL', 0.0001, 0),
      ('kL', 'Kiloliters', 'SI', 'Volume', 'kL', 1, 0),
      ('ML', 'Megaliters', 'SI', 'Volume', 'ML', 1000, 0),
      ('GL', 'Gigaliters', 'SI', 'Volume', 'GL', 1000000, 0),
      ('tsp', 'Teaspoons', 'Imperial', 'Volume', 'tsp', 4.9e-06, 0),
      ('tbsp', 'Tablespoons', 'Imperial', 'Volume', 'tbsp', 1.48e-05, 0),
      ('floz', 'Fluid ounces', 'Imperial', 'Volume', 'fl oz', 2.95735e-05, 0),
      ('shot', 'Shots', 'Imperial', 'Volume', 'shot', 4.436025e-05, 0),
      ('c', 'Cups', 'Imperial', 'Volume', 'c', 0.000236588, 0),
      ('pt', 'Pints', 'Imperial', 'Volume', 'pt', 0.000473176, 0),
      ('qt', 'Quarts', 'Imperial', 'Volume', 'qt', 0.000946352, 0),
      ('gal', 'Gallons', 'Imperial', 'Volume', 'gal', 0.003785408, 0),
      ('yd3', 'Cu. Yards', 'Imperial', 'Volume', 'yd³', 0.764555, 0),
      ('bbl', 'Oil barrels', 'Imperial', 'Volume', 'bbl', 0.159, 0),
      ('acft', 'Acre-Foot', 'Imperial', 'Volume', 'ac-ft', 1233.48, 0),
      ('pv', 'Planck volume', 'Scientific', 'Volume', 'Vₚ', 4.222e-105, 0),
      -- Force
      ('N', 'Newton', 'SI', 'Force', 'N', 1, 0),
      ('kN', 'Kilonewton', 'SI', 'Force', 'kN', 1000, 0),
      ('MN', 'Meganewton', 'SI', 'Force', 'MN', 1000000, 0),
      ('GN', 'Giganewton', 'SI', 'Force', 'GN', 1000000000, 0),
      ('mN', 'Millinewton', 'SI', 'Force', 'mN', 0.001, 0),
      ('µn', 'Micronewton', 'SI', 'Force', 'µN', 1e-06, 0),
      ('nN', 'Nanonewton', 'SI', 'Force', 'nN', 1e-09, 0),
      ('pN', 'Piconewton', 'SI', 'Force', 'pN', 1e-12, 0),
      ('dyne', 'Dyne', 'Scientific', 'Force', 'dyn', 1e-05, 0),
      ('kgf', 'Kilogram-force', 'Scientific', 'Force', 'kgf', 9.80665, 0),
      ('gf', 'Gram-force', 'Scientific', 'Force', 'gf', 0.00980665, 0),
      ('tf', 'Tonne-force', 'Scientific', 'Force', 'tf', 9806.65, 0),
      ('lbf', 'Pound-force', 'Imperial', 'Force', 'lbf', 4.44822, 0),
      ('kip', 'Kilopound', 'Imperial', 'Force', 'kip', 4448.22, 0),
      ('ozf', 'Ounce-force', 'Imperial', 'Force', 'ozf', 0.27801375, 0),
      ('stf', 'Short Ton-force', 'Imperial', 'Force', 'stf', 8896.44, 0),
      ('ltf', 'Long Ton-force', 'Imperial', 'Force', 'ltf', 9964.0128, 0),
      ('pdl', 'Poundal', 'Imperial', 'Force', 'pdl', 0.13825, 0),
      ('pf', 'Planck Force', 'Scientific', 'Force', 'Fₚ', 1.2103e+44, 0);
